main/default/objects/Platform_Lead__c/Platform_Lead__c.object-meta.xml
<CustomObject>
    <label>Platform Lead</label>
    <nameField>
        <displayFormat>PL-{0000000}</displayFormat>
        <label>Platform Lead Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Platform_Lead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platform Leads</relationshipLabel>
    <relationshipName>Platform_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Platform_Lead__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Platform Leads</relationshipLabel>
    <relationshipName>Platform_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Platform_Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Platform Leads</relationshipLabel>
    <relationshipName>Platform_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/NewLeadController.cls
public class NewLeadController {
  @AuraEnabled   
  public static id saveRecordApex( Platform_Lead__c p, list<string> accid, list<string>  conid, list<string>  leadid) {
   //takes account of bad mapping between js and apex in Lightning for lookups
      if(accid.size()>0){p.Account__c=accid[0];}
      if(conid.size()>0){p.Contact__c=conid[0];}
      if(leadid.size()>0){p.Lead__c=leadid[0];}
      insert p;
      return p.id;}
  @AuraEnabled
  public static List<ListView> getListViews() {
    List<ListView> listviews = [SELECT Id, Name FROM ListView WHERE SobjectType = 'Platform_Lead__c'];
    return listviews;}}